version: '3.8'

services:
  db:
    image: postgres:15
    container_name: login_db
    restart: always
    environment:
      POSTGRES_DB: login_system
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 4444
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
